services:
  openplc:
    build: .
    container_name: openplc_v3
    ports:
      - "8080:8080"
    privileged: true
    restart: unless-stopped

  gateway:
    build: ./openplc/gateway
    container_name: plc_gateway
    ports:
      - "3001:3001"
    environment:
      - PLC_HOST=openplc
      - PLC_PORT=502
      - PLC_API_HOST=openplc
      - PLC_API_PORT=8443
      - PLC_API_USER=PiiJar
      - PLC_API_PASS=!T0s1v41k33!
      - API_PORT=3001
      - POLL_MS=100
    volumes:
      - ./customers:/data/customers:ro
    depends_on:
      - openplc
    restart: unless-stopped

  visualization:
    build: ./PLC Simulator/visualization
    container_name: plc_ui
    ports:
      - "5173:80"
    depends_on:
      - gateway
      - simulator
    restart: unless-stopped

  simulator:
    build:
      context: ./PLC Simulator
      dockerfile: containers/simulator/Dockerfile
    container_name: plc_simulator
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - PLANT_TEMPLATES_DIR=/data/plant_templates
      - CUSTOMERS_DIR=/data/customers
    volumes:
      - ./customers:/data/customers
      - ./plant_templates:/data/plant_templates
    restart: unless-stopped
